### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by fulin426** [fulin426/Issues-Hunt#4]
I would like to know what people's thoughts are on the application so far. 

Is it easy to use? 
Has it been helpful in searching for issues? 
How can it be improved? 

Please comment and discuss below.

**Comment by lily-law** [comment]
It is nice and easy, though could use some feedback when selecting filters just to make it clear which are selected. 

Today I spent awhile before finding this, trying to find somewhere to start on GitHub. After having a bath and feeling a little useless I found this. I need to spend a day with it to try searching. But setting it up one issue found me. 

Very minor really but it would be better to make it work out the box without needing to change lines for the (api) Keys. So I'll try sending a pull request with that implemented.

**Comment by fulin426** [comment]
Hi, 

Thank you for checking out App! The idea started when I was looking for open issues to solve and I had a tough time using default GitHub search features. I would look through endless repos to only find the issues are out of my league or the easy ones were already claimed.  I wanted to simplify the search process by searching for issues only and practice using React. Filtering by label or language can be found in the advanced section of the search, but it is still somewhat cumbersome.

Although, this was mainly done to replace one of my old portfolio projects, I'm glad it could be of use to someone!

**Comment by jeffslofish** [comment]
Hello, I just found your repo and it is similar to mine: https://github.com/jeffslofish/open-source-help-wanted. I was wondering if you would like to collaborate in some way?

**Comment by fulin426** [comment]
@jeffslofish 

Thanks for finding my repo. Unfortunately, this is something I put together last year as way to practice React and I don't plan to revisiting it as of now. Feel free to take a look at the code or features for inspiration in your own project.
