### ISSUE TITLE
Create feedback after search

### ISSUE THREAD

**Issue by fulin426** [fulin426/Issues-Hunt#6]
create some sort of feedback after the search has been completed in the drop-down menu. This will allow users to see which parameters they are using besides the check mark.

**Comment by Doaa-Ismael** [comment]
Could I work on this?

**Comment by fulin426** [comment]
Sure thing! I created a screenshot of the idea I had. I was thinking of having a label, similar to the clear all label, pop up each time a user clicks the dropdown. They should be able to click the label and the search results update. 

https://planogy.com/Whe15k1Oi6ns7gV86W0qw

setState takes an optional callback function. So let's say I want to clear the language sort options and call the API again.

this.setState({ language: ''}, () => this.callAPI());

Learn more about it here:
https://medium.learnreact.com/setstate-takes-a-callback-1f71ad5d2296

I haven't updated this repo in a few months, but I'll be happy to take any suggestions.
