### ISSUE TITLE
Add project name to each issue

### ISSUE THREAD

**Issue by Bersam** [fulin426/Issues-Hunt#7]
Adding project name to each issue would be really helpful. Github shows project name as well if you use github's own search engine.

**Comment by fulin426** [comment]
I'll take a look into this issue. The API does provide the project details. I'll work on this weekend. Thanks for opening up an issue.

**Comment by fulin426** [comment]
@Bersam Thanks for the suggestion! I actually had that functionality coded, but I commented it out thinking that it would be too much information. I uploaded a new version on Heroku just now.
